# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 034932754a08aafbf323bd2c3d9951482852238a5485293f0ad910dc1dfd5503b0fe06c9c2a46c82e3bbb336eacf4615af8557317d271a6a2f5c1a944d68ede6

test:
  secret_key_base: 8a1e22ae5edf1f66473d356cca36bfb700052656e8cb5c83cdeb43236abe6560d27c679a001af85f1b9c491de4967563eb3d7d7efc5c18969a8a0a73d0078f12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
