# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a478c20fa4721f798c188f6d0cbea6fd4551d5d1601ff509bda9dd16bddc360fa23b12b6ae54dfd8f727682cfcb5f24f182cb307cb35d8d517768a8ecb63d723

test:
  secret_key_base: c1b17332564e8b1abb9780105c795cfb2ee519d7c953fb5b296dea760edfccf575138ac73a24343dde181de8769618446089319352c00348ff86ab8c183483bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
