# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98860b415494065dc79d0e70e4da2f11d4085da45bdfd21aa1d0f398575f31782eebb63d78b198149f3e229602875d80293a5336ab0111ca333fa5a7110506a8

test:
  secret_key_base: 020e68e0f5be5b246e04a0e99948a3384b9ddd8564726865217054f1d8b145edc179efd7fcefd86dc02fc3024694cec2bb82b0f0e94503fc5a7582b690a37e51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
