# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80515c6484463d40d0d3611faca7e4d294b59b97a5e9b92003c0ba3c48c5289a916084730c83e6ffbddbdd2d7a162d292e8be4a8142265fc1b598b0857fb1867

test:
  secret_key_base: a3d9ff825695fc022e691034c57c920c1f497232d413a5cac5d4c8cb671a57d199f694d636b6a9bbd8d81a9a9eeae4bde8c6a3fde6e3ab645787e3d6c51d11e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
