# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 065bf40282b31d5b01d77504bed4017b004802ee458a23cbd0feb014b0a57680feaa7215770d7a51c0ae05d9f6a1e7ac5016a5264572780ccd7fef593aaa5406

test:
  secret_key_base: 1495775623cbfaee7d46890d8db1a8931bf380c6ddb2ece30bd131e39ae2bbefd828942d982d54bf226920593fecda51e0d8863d6eeb9e2c34a597ba29af1367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
