# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ab6aedc214cc6cea70c1536f3a4caaceb7ce90ae0a2e8082280fcb19d595653c39632cd3dca120b1ad898965f1384b6fc880f3dba3004af92336a7e3d165cf

test:
  secret_key_base: f8ebc6cef0762507eb1be5b9fe32b96739d4a7da3952e9de2017d52dc5789ca4b67de903934bc31a0a0884ef24cdebf06cace1c8faf970a048346f5c5c0b9a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
